export const requestConstants = {
    GET_REQUESTS_REQUEST:'GET_USER_REQUESTS_REQUEST',
    GET_REQUESTS_SILENTLY_REQUEST:'GET_USER_REQUESTS_SILENTLY_REQUEST',
    GET_REQUESTS_FAILURE:'GET_USER_REQUESTS_FAILURE',
    GET_REQUESTS_SUCCESS:'GET_USER_REQUESTS_SUCCESS',

    DEPLOY_REQUEST_REQUEST:'DEPLOY_USER_REQUEST_REQUEST',
    DEPLOY_REQUEST_FAILURE:'DEPLOY_USER_REQUEST_FAILURE',
    DEPLOY_REQUEST_SUCCESS:'DEPLOY_USER_REQUEST_SUCCESS',

    FINISH_REQUEST_REQUEST:'FINISH_USER_REQUEST_REQUEST',
    FINISH_REQUEST_FAILURE:'FINISH_USER_REQUEST_FAILURE',
    FINISH_REQUEST_SUCCESS:'FINISH_USER_REQUEST_SUCCESS',

    REJECT_REQUEST_REQUEST:'REJECT_USER_REQUEST_REQUEST',
    REJECT_REQUEST_FAILURE:'REJECT_USER_REQUEST_FAILURE',
    REJECT_REQUEST_SUCCESS:'REJECT_USER_REQUEST_SUCCESS',

    SET_ACTIVE_REQUEST:'SET_ACTIVE_USER_REQUEST',
    CLEAR_ACTIVE_REQUEST:'CLEAR_ACTIVE_USER_REQUEST'
};